import type { Patient } from "@/lib/types";

export const initialPatients: Patient[] = [
  {
    id: "p-1",
    nombreCompleto: "María Elena Fernández",
    documento: "28.456.789",
    fechaNacimiento: "1985-03-14",
    sexo: "femenino",
    telefono: "+54 11 4455-2010",
    email: "maria.fernandez@example.com",
    direccion: "Av. Rivadavia 4520, CABA",
    obraSocial: "OSDE 310",
    contactoEmergencia: { nombre: "Roberto Fernández", telefono: "+54 11 4455-2011" },
    consultas: [
      {
        id: "c-1-1",
        fecha: "2026-01-12T09:30:00",
        medico: "Dra. Valentina Cruz",
        motivoConsulta: "Cefalea recurrente",
        sintomas: ["Dolor de cabeza pulsátil", "Fatiga", "Sensibilidad a la luz"],
        diagnostico: "Cefalea tensional",
        indicaciones: "Ibuprofeno 400mg cada 8hs por 3 días. Control de hidratación y sueño.",
        notas: "Paciente refiere estrés laboral elevado en las últimas semanas.",
      },
      {
        id: "c-1-2",
        fecha: "2026-03-02T11:00:00",
        medico: "Dr. Martín Suárez",
        motivoConsulta: "Fatiga persistente",
        sintomas: ["Cansancio generalizado", "Dolor de cabeza leve", "Dificultad para concentrarse"],
        diagnostico: "Astenia inespecífica, se solicita laboratorio de rutina",
        indicaciones: "Análisis de sangre completo. Reevaluar en 3 semanas con resultados.",
        notas: "Sin antecedentes relevantes. Se descarta anemia por interrogatorio.",
      },
      {
        id: "c-1-3",
        fecha: "2026-04-20T10:15:00",
        medico: "Dra. Valentina Cruz",
        motivoConsulta: "Control con resultados de laboratorio",
        sintomas: ["Cansancio generalizado", "Dolor de cabeza ocasional"],
        diagnostico: "Laboratorio dentro de parámetros normales",
        indicaciones: "Continuar con hábitos de sueño e hidratación. Sin medicación nueva.",
        notas: "Persisten los síntomas sin causa orgánica clara identificada hasta el momento.",
      },
      {
        id: "c-1-4",
        fecha: "2026-06-18T08:45:00",
        medico: "Dr. Ezequiel Paz",
        motivoConsulta: "Dolor de cabeza y fatiga, cuarta consulta en el año",
        sintomas: ["Dolor de cabeza pulsátil", "Fatiga", "Irritabilidad"],
        diagnostico: "Cefalea tensional recurrente",
        indicaciones: "Se sugiere evaluación por neurología para descartar otras causas.",
        notas: "Cuarta consulta con síntomas similares sin diagnóstico definitivo unificado.",
      },
    ],
    aiInsight: {
      nivel: "alerta",
      resumen:
        "Se detectó un patrón recurrente de cefalea y fatiga en 4 consultas distintas a lo largo del año, atendidas por 3 médicos diferentes, sin que se haya establecido una causa común.",
      hallazgos: [
        "Síntoma 'dolor de cabeza' presente en 4 de 4 consultas registradas.",
        "Síntoma 'fatiga' presente en 3 de 4 consultas, sin diagnóstico unificado.",
        "Laboratorio de rutina normal: sugiere descartar causas no orgánicas (estrés, sueño) o profundizar estudios neurológicos.",
      ],
      generadoEl: "2026-06-18T12:00:00",
    },
  },
  {
    id: "p-2",
    nombreCompleto: "Jorge Alberto Gómez",
    documento: "22.114.532",
    fechaNacimiento: "1970-07-22",
    sexo: "masculino",
    telefono: "+54 11 4522-3387",
    email: "jorge.gomez@example.com",
    direccion: "Calle Mitre 1230, San Isidro",
    obraSocial: "Swiss Medical",
    contactoEmergencia: { nombre: "Silvia Gómez", telefono: "+54 11 4522-3388" },
    consultas: [
      {
        id: "c-2-1",
        fecha: "2026-02-05T14:00:00",
        medico: "Dr. Martín Suárez",
        motivoConsulta: "Control de rutina",
        sintomas: ["Ninguno referido"],
        diagnostico: "Presión arterial 135/88, levemente elevada",
        indicaciones: "Reducir consumo de sodio. Actividad física moderada 3 veces por semana.",
        notas: "Primer registro de presión levemente elevada en el paciente.",
      },
      {
        id: "c-2-2",
        fecha: "2026-04-15T09:00:00",
        medico: "Dra. Valentina Cruz",
        motivoConsulta: "Seguimiento de presión arterial",
        sintomas: ["Ninguno referido"],
        diagnostico: "Presión arterial 142/90",
        indicaciones: "Iniciar monitoreo domiciliario diario. Control en 6 semanas.",
        notas: "Paciente refiere dificultad para sostener la dieta baja en sodio.",
      },
      {
        id: "c-2-3",
        fecha: "2026-06-01T10:30:00",
        medico: "Dr. Martín Suárez",
        motivoConsulta: "Control de presión arterial",
        sintomas: ["Ninguno referido"],
        diagnostico: "Presión arterial 145/92, tendencia sostenida al alza",
        indicaciones: "Se inicia tratamiento farmacológico con Enalapril 10mg/día.",
        notas: "Se discute con el paciente la importancia de la adherencia al tratamiento.",
      },
    ],
    aiInsight: {
      nivel: "info",
      resumen:
        "La presión arterial del paciente muestra una tendencia sostenida al alza a lo largo de 3 controles consecutivos.",
      hallazgos: [
        "Presión arterial en aumento progresivo: 135/88 → 142/90 → 145/92 en 4 meses.",
        "Se inició tratamiento farmacológico en la última consulta; sugerido continuar monitoreo estrecho.",
      ],
      generadoEl: "2026-06-01T12:00:00",
    },
  },
  {
    id: "p-3",
    nombreCompleto: "Lucía Belén Martínez",
    documento: "35.987.612",
    fechaNacimiento: "1998-11-05",
    sexo: "femenino",
    telefono: "+54 11 3344-9021",
    email: "lucia.martinez@example.com",
    direccion: "Pasaje Los Alerces 87, Vicente López",
    contactoEmergencia: { nombre: "Carla Martínez", telefono: "+54 11 3344-9022" },
    consultas: [
      {
        id: "c-3-1",
        fecha: "2026-05-10T16:00:00",
        medico: "Dra. Valentina Cruz",
        motivoConsulta: "Dolor de garganta y fiebre",
        sintomas: ["Odinofagia", "Fiebre 38.5°C", "Congestión nasal"],
        diagnostico: "Faringitis viral",
        indicaciones: "Paracetamol 500mg cada 8hs. Reposo e hidratación. Reconsultar si persiste más de 5 días.",
        notas: "Cuadro leve, evolución esperable favorable.",
      },
      {
        id: "c-3-2",
        fecha: "2026-07-02T11:30:00",
        medico: "Dr. Ezequiel Paz",
        motivoConsulta: "Control ginecológico anual",
        sintomas: ["Ninguno referido"],
        diagnostico: "Examen sin hallazgos patológicos",
        indicaciones: "Continuar controles anuales de rutina.",
        notas: "Paciente al día con estudios preventivos.",
      },
    ],
  },
  {
    id: "p-4",
    nombreCompleto: "Carlos Alberto Rodríguez",
    documento: "18.765.432",
    fechaNacimiento: "1962-01-30",
    sexo: "masculino",
    telefono: "+54 11 4988-6712",
    email: "carlos.rodriguez@example.com",
    direccion: "Av. Cabildo 3345, CABA",
    obraSocial: "PAMI",
    contactoEmergencia: { nombre: "Marta Rodríguez", telefono: "+54 11 4988-6713" },
    consultas: [
      {
        id: "c-4-1",
        fecha: "2026-01-20T08:00:00",
        medico: "Dr. Martín Suárez",
        motivoConsulta: "Dolor abdominal difuso",
        sintomas: ["Dolor abdominal leve", "Distensión"],
        diagnostico: "Dispepsia funcional",
        indicaciones: "Dieta blanda por 1 semana. Omeprazol 20mg/día.",
        notas: "Sin signos de alarma en el examen físico.",
      },
      {
        id: "c-4-2",
        fecha: "2026-03-11T09:15:00",
        medico: "Dra. Valentina Cruz",
        motivoConsulta: "Persistencia de molestias digestivas",
        sintomas: ["Dolor abdominal leve", "Pérdida de apetito"],
        diagnostico: "Gastritis leve",
        indicaciones: "Continuar Omeprazol 20mg/día por 4 semanas más. Evitar irritantes gástricos.",
        notas: "Paciente refiere haber bajado 2kg desde la última consulta.",
      },
      {
        id: "c-4-3",
        fecha: "2026-05-28T10:00:00",
        medico: "Dr. Ezequiel Paz",
        motivoConsulta: "Dolor abdominal y baja de peso",
        sintomas: ["Dolor abdominal difuso", "Pérdida de peso", "Fatiga leve"],
        diagnostico: "Se solicitan estudios complementarios (laboratorio y ecografía abdominal)",
        indicaciones: "Laboratorio completo con perfil hepático. Ecografía abdominal. Turno de control en 2 semanas.",
        notas: "Pérdida de peso acumulada de aproximadamente 4kg en 4 meses, sin cambios dietarios intencionales.",
      },
      {
        id: "c-4-4",
        fecha: "2026-06-25T09:30:00",
        medico: "Dr. Martín Suárez",
        motivoConsulta: "Control con estudios complementarios",
        sintomas: ["Dolor abdominal difuso", "Pérdida de peso"],
        diagnostico: "Estudios sin hallazgos concluyentes, se deriva a gastroenterología",
        indicaciones: "Derivación a gastroenterología para evaluación endoscópica.",
        notas: "Persiste la pérdida de peso sin causa clara identificada en 4 consultas.",
      },
    ],
    aiInsight: {
      nivel: "alerta",
      resumen:
        "El paciente presenta dolor abdominal recurrente y pérdida de peso progresiva documentada en 4 consultas, con diagnósticos leves que no explican completamente el cuadro.",
      hallazgos: [
        "Pérdida de peso sostenida (~4kg) reportada en 3 consultas consecutivas sin causa dietaria.",
        "Síntoma 'dolor abdominal' presente en las 4 consultas registradas con diagnósticos distintos cada vez.",
        "Recién en la última consulta se deriva a un especialista: se recomienda priorizar el seguimiento gastroenterológico.",
      ],
      generadoEl: "2026-06-25T11:00:00",
    },
  },
  {
    id: "p-5",
    nombreCompleto: "Ana Sofía Torres",
    documento: "40.222.111",
    fechaNacimiento: "2001-09-09",
    sexo: "femenino",
    telefono: "+54 11 6655-1029",
    email: "ana.torres@example.com",
    direccion: "Calle Güemes 550, Olivos",
    obraSocial: "Galeno",
    contactoEmergencia: { nombre: "Pedro Torres", telefono: "+54 11 6655-1030" },
    consultas: [
      {
        id: "c-5-1",
        fecha: "2026-02-14T15:00:00",
        medico: "Dra. Valentina Cruz",
        motivoConsulta: "Erupción cutánea en brazos",
        sintomas: ["Ronchas rojas", "Picazón leve"],
        diagnostico: "Dermatitis de contacto",
        indicaciones: "Crema con hidrocortisona 1% dos veces al día por 7 días. Evitar el alérgeno sospechado.",
        notas: "Posible relación con detergente nuevo, se recomienda cambio de producto.",
      },
      {
        id: "c-5-2",
        fecha: "2026-04-30T13:45:00",
        medico: "Dr. Ezequiel Paz",
        motivoConsulta: "Control post-tratamiento dermatológico",
        sintomas: ["Sin picazón", "Piel con leve descamación residual"],
        diagnostico: "Resolución favorable de dermatitis de contacto",
        indicaciones: "Hidratante corporal diario. Alta del cuadro.",
        notas: "Buena adherencia al tratamiento indicado.",
      },
      {
        id: "c-5-3",
        fecha: "2026-07-18T10:00:00",
        medico: "Dr. Martín Suárez",
        motivoConsulta: "Chequeo general anual",
        sintomas: ["Ninguno referido"],
        diagnostico: "Examen físico sin hallazgos relevantes",
        indicaciones: "Continuar controles preventivos anuales. Solicitar laboratorio de rutina.",
        notas: "Paciente sana, sin antecedentes de relevancia.",
      },
    ],
    aiInsight: {
      nivel: "info",
      resumen:
        "No se identificaron patrones de riesgo entre las consultas registradas; la evolución de los cuadros fue favorable.",
      hallazgos: [
        "El episodio de dermatitis de contacto tuvo resolución completa confirmada en el control posterior.",
        "Sin síntomas recurrentes entre consultas de distintos motivos.",
      ],
      generadoEl: "2026-07-18T11:30:00",
    },
  },
];
